server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shiro?serverTimezone=GMT%2B8&ampuseUnicode=true&ampcharacterEncoding=utf-8&ampuseSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    database: mysql
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        enable_lazy_load_no_trans: true
  ## jsp
  mvc:
    view:
      prefix: /pages/
      suffix: .jsp
## mybatis
mybatis:
  mapper-locations: mappers/*.xml
  type-aliases-package: com.xjsaber.java.shiro.model

